language: python

matrix:
  include:
    - python: 3.4
      dist: trusty
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial  # required for Python >= 3.7

addons:
  apt:
    sources:
      - sourceline: 'ppa:pmjdebruijn/gcc-avr-release'
    packages:
      - avr-libc
      - gcc-avr
      - srecord

before_install:
  # avra
  - git clone https://github.com/mnaberez/avra.git
  - make -C avra/src -f makefiles/Makefile.linux
  - export PATH=$PATH:$PWD/avra/src

  # asxxxx
  - wget -q -U travis http://6502.org/tools/asm/asxv5p31.zip
  - unzip -q asxv5p31.zip
  - make -C asxv5pxx/asxmak/linux/build all
  - export PATH=$PATH:$PWD/asxv5pxx/asxmak/linux/build

script:
  - make -C faceplate_emulator/firmware
  - python faceplate_emulator/host/setup.py test -q
  - make -C kwp1281_tool/firmware
  - make -C reverse_engineering/vw_gamma_5_technisat/disasm
  - make -C reverse_engineering/vw_premium_4_clarion/disasm/pu1666a_mainmcu
  - make -C reverse_engineering/vw_premium_4_clarion/disasm/pu1666a_submcu
  - make -C reverse_engineering/vw_premium_5_delco/disasm
  - make -C reverse_engineering/vw_premium_5_delco/custom/baudrate
  - make -C reverse_engineering/vw_premium_5_delco/custom/dumpram
  - make -C reverse_engineering/vw_premium_5_delco/custom/faultcodes
  - make -C reverse_engineering/vw_premium_5_delco/custom/loopback_irq
  - make -C reverse_engineering/vw_premium_5_delco/custom/loopback_poll
  - make -C reverse_engineering/vw_premium_5_delco/custom/loopback_radio
  - make -C reverse_engineering/vw_premium_5_delco/custom/remote
  - make -C reverse_engineering/vw_rhapsody_technisat/disasm
  - make -C volume_monitor/firmware
  - make -C tape_emulator/firmware
